[general]
import = ["~/dotfiles/alacritty/dracula.toml"]

[font]

normal.family = "0xProto Nerd Font"
bold.family = "0xProto Nerd Font"
italic.family = "0xProto Nerd Font"
bold_italic.family = "0xProto Nerd Font"

[keyboard]

bindings = [
   { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" }
]

