# The basic colors
foreground              #efdfe1
background              #191113
selection_foreground    #efdfe1
selection_background    #e2bdc7

# Cursor colors
cursor                  #d5c2c6
cursor_text_color       #191113

# URL underline color when hovering with mouse
url_color               #ffb0c9

# Kitty window border colors
active_border_color     #ffb0c9
inactive_border_color   #514347
bell_border_color       #efbd94

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #191113
active_tab_background   #ffb0c9
inactive_tab_foreground #efdfe1
inactive_tab_background #261d20
tab_bar_background      #191113

# Colors for marks (marked text in the terminal)
mark1_foreground #191113
mark1_background #ffb0c9
mark2_foreground #191113
mark2_background #6f3349
mark3_foreground #191113
mark3_background #e2bdc7

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

# magenta
color5  #F5C2E7
color13 #F5C2E7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8
